### ISSUE TITLE
アカウント名・パスワード忘れしても大丈夫なようにする

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/dashboard-ui#103]
パスワード再発行？かな？

**Comment by himaratsu** [comment]
Parseの持つ機能をつかっての実装にしましょ！

**Comment by shoma2da** [comment]
dashboard-api で使ってるParseクライアントでも簡単に利用できそうだ！
https://github.com/adelevie/parse-ruby-client/blob/45d99ff6713633104a7ec12af37a8dd9a4cefb71/features.md#requesting-a-password-reset

dashboard-api に新しくAPI１個作って dashboard から呼び出してもらう形で良いかな？

**Comment by himaratsu** [comment]
そうしよう！

**Comment by shoma2da** [comment]
https://github.com/meyasubaco/dashboard-api/pull/74

API側の対応はできた感じか！

**Comment by shoma2da** [comment]
ここから先の対応はzatsuで相談しましょー！
