### ISSUE TITLE
android-sdk導入時のバージョンが古い

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/dashboard-ui#104]
![image](https://cloud.githubusercontent.com/assets/2342648/12050449/13f0ccc8-af39-11e5-9d05-d390ffeb7259.png)

頻繁に更新されるので`+`を使っても良いかも...

**Comment by shibe97** [comment]
@shoma2da こちらどうすれば良いでしょう？

**Comment by shoma2da** [comment]
とりあえず現状は `0.8.0` でお願いします！

**Comment by shibe97** [comment]
@shoma2da 了解です〜！
