### ISSUE TITLE
【質問】bundle.jsってcommitすべき？＞Githubへのプッシュ、プルを素早くしたい

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/dashboard-ui#114]
@shibe97 
https://github.com/shoma2da/dashboard-ui/blob/sample/dist/bundle.js
↑
こちらのファイルってビルドして生成されるものな気がするんですが、commitに含めるべきものなんでしょうか？

結構サイズ大きいのでプッシュ＆プルに時間かかるのと、
ビルド環境（npmのバージョン？）によってファイル内容も変わるので、予期せぬエラーにつながったりしないのか疑問に思いました。

全然急ぎでないのでIssueで登録としておきます！

**Comment by shibe97** [comment]
@shoma2da 
すいません、おっしゃる通りでcommitに含めるべきではないと思います。

その場合って、heroku側でビルドすることになるのかな？
そこらへんがよく分かっていないんだけど、分かります？？

**Comment by shoma2da** [comment]
おー、やっぱし :star: 

現状もデプロイするときにheroku側でビルドしていて、herokuはそれを使ってるみたいだね！
https://travis-ci.org/meyasubaco/dashboard-ui/builds/102916893#L824
→もしかしたらファイルを単純に削除するだけで良いかもです。

**Comment by shibe97** [comment]
おー、そうなんだ！
じゃあ削除するだけだね！
.gitignoreに追加しておきます！

**Comment by shoma2da** [comment]
https://github.com/meyasubaco/dashboard-ui/pull/115 で対応中...

**Comment by shoma2da** [comment]
close!!
