### ISSUE TITLE
user-api のエンドポイント変更に追従する

### ISSUE THREAD

**Issue by himaratsu** [meyasubaco/dashboard-ui#17]
「ユーザーごとのApplication一覧」のエンドポイントが変わりました：

handshakejp/user-api#19

**Comment by shoma2da** [comment]
具体的な変更点はこちら。
https://github.com/handshakejp/dashboard-api/pull/31/files

まだ使ってない？？

**Comment by shoma2da** [comment]
終わってるっぽいかな！
