### ISSUE TITLE
「特定商取引法に基づく表記」画面を作る

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/dashboard-ui#81]
https://handshakejp.slack.com/archives/general/p1448459762000128

**Comment by shoma2da** [comment]
qiita : https://qiita.com/asct
hatena : http://hatenacorp.jp/tokutei
cookpad : https://cookpad.com/terms/tokutei
tabelog : http://user-help.tabelog.com/legal/
webpay : https://webpay.jp/company
esa.io : https://docs.esa.io/posts/39

**Comment by shibe97** [comment]
* 事業者名のところはサービス名で良いのか？
* 責任者は松田承一？
* 住所と電話番号

**Comment by shoma2da** [comment]
> 事業者名のところはサービス名で良いのか？

良いと思います！

> 責任者は松田承一？

とりあえずそれでも大丈夫です！

> 住所と電話番号

Slackで送ります！

**Comment by shoma2da** [comment]
Slack書きました！
https://handshakejp.slack.com/archives/github/p1449109713000072
