### ISSUE TITLE
【課金】課金をやめられるようにする

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/dashboard-ui#87]
リンク設置してdashboard-apiにリクエスト送信の流れ？
相談しながら進めましょう。

**Comment by himaratsu** [comment]
* DB を変更
* Webpay にキャンセルリクエスト

**Comment by shoma2da** [comment]
https://github.com/meyasubaco/dashboard-api/pull/103 で対応しました。

Deleteメソッドで、'http://SERVER:PORT/user/:user_id/payment' にアクセスしてください。
